[package]
name = "process-diagnostics-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
serde_json = "1.0"

[dependencies.process-diagnostics]
path = ".."

[[bin]]
name = "transcript"
path = "fuzz_targets/transcript.rs"
test = false
doc = false
bench = false
